name: 01-building-blockes
on: workflow_dispatch
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "Hello, World!"
    echo-hello2:
        runs-on: ubuntu-latest
        steps:
            - name: failed
              run: |
                echo "Failed run!"
                exit 0
